# Generated by Django 5.2.8 on 2026-01-13 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_alter_account_id_alter_fiscalyear_id_and_more'),
        ('users', '0010_institution_sri_url_authorization_prod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=17, verbose_name='Número Comprobante')),
                ('authorization_code', models.CharField(blank=True, max_length=49, verbose_name='Clave Acceso / Autorización')),
                ('issue_date', models.DateField(verbose_name='Fecha Emisión')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('sustento_tributario', models.CharField(default='01', max_length=2, verbose_name='Cod. Sustento')),
                ('payment_method', models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero')], default='20', max_length=50)),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_15', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_no_obj', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('VALIDATED', 'Validada/Contabilizada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20)),
                ('journal_entry_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='users.institution')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(choices=[(0, '0%'), (15, '15%')], decimal_places=2, default=0, max_digits=5)),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='Cuenta de Gasto')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=20, verbose_name='Identificación (RUC/CI)')),
                ('tax_id_type', models.CharField(choices=[('RUC', 'RUC'), ('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], default='RUC', max_length=20)),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Comercial')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('is_special_taxpayer', models.BooleanField(default=False, verbose_name='Es Contribuyente Especial')),
                ('establishment_code', models.CharField(blank=True, default='001', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='users.institution')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'unique_together': {('institution', 'tax_id')},
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchases.supplier'),
        ),
        migrations.CreateModel(
            name='Withholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=17, verbose_name='Número Retención')),
                ('issue_date', models.DateField()),
                ('access_key', models.CharField(blank=True, max_length=49, null=True, unique=True)),
                ('ret_renta_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ret_renta_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ret_renta_code', models.CharField(blank=True, max_length=10, verbose_name='Cod. Retención Renta')),
                ('ret_iva_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ret_iva_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sri_status', models.CharField(default='PENDING', max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.institution')),
                ('purchase_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withholding', to='purchases.purchaseinvoice')),
            ],
        ),
    ]
