# Generated by Django 5.2.11 on 2026-02-23 19:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('users', '0011_alter_user_groups_alter_user_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=17, unique=True, verbose_name='Número Nota Crédito')),
                ('authorization_code', models.CharField(blank=True, max_length=49, verbose_name='Clave Acceso NC')),
                ('issue_date', models.DateField(verbose_name='Fecha Emisión')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo de Modificación')),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_no_obj', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_credit_notes', to='users.institution')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='purchases.purchaseinvoice', verbose_name='Factura Modificada')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=17, unique=True, verbose_name='Número Nota Débito')),
                ('authorization_code', models.CharField(blank=True, max_length=49, verbose_name='Clave Acceso ND')),
                ('issue_date', models.DateField(verbose_name='Fecha Emisión')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo de Modificación')),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_no_obj', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_debit_notes', to='users.institution')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='purchases.purchaseinvoice', verbose_name='Factura Modificada')),
            ],
        ),
    ]
