# Generated by Django 6.0.2 on 2026-04-28 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecreditnote',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='purchaseliquidation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='purchaseliquidationitem',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='withholding',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
    ]
