# Generated by Django 5.2.12 on 2026-03-04 16:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_fixedasset_depreciation'),
        ('purchases', '0002_purchasecreditnote_purchasedebitnote'),
        ('users', '0011_alter_user_groups_alter_user_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLiquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=17, verbose_name='Número Comprobante')),
                ('authorization_code', models.CharField(blank=True, max_length=49, verbose_name='Clave Acceso / Autorización')),
                ('issue_date', models.DateField(verbose_name='Fecha Emisión')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('sustento_tributario', models.CharField(default='01', max_length=2, verbose_name='Cod. Sustento')),
                ('payment_method', models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero')], default='20', max_length=50)),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_no_obj', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('VALIDATED', 'Validada/Contabilizada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20)),
                ('journal_entry_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_liquidations', to='users.institution')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidations', to='purchases.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLiquidationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('15'), '15%')], decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='Cuenta de Gasto')),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseliquidation')),
            ],
        ),
    ]
