# Generated by Django 5.2.13 on 2026-04-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(max_length=255)),
                ('smtp_password_encrypted', models.TextField()),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('sender_name', models.CharField(help_text='Nombre que aparecerá en el envío', max_length=255)),
                ('sender_email', models.CharField(help_text='Email que aparecerá como remitente', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(blank=True, help_text='ID de referencia (ej: factura_id)', max_length=100)),
                ('module_origin', models.CharField(blank=True, help_text='Módulo originador', max_length=50)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'verbose_name': 'Log de Email',
                'verbose_name_plural': 'Logs de Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('code', models.CharField(choices=[('invoice_sent', 'Factura Enviada'), ('payment_reminder', 'Recordatorio de Pago'), ('grades_ready', 'Calificaciones Listas'), ('parent_notice', 'Aviso a Padres'), ('password_reset', 'Recuperar Contraseña'), ('welcome', 'Bienvenida')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
                'unique_together': {('institution', 'code')},
            },
        ),
    ]
