# Generated by Django 6.0.2 on 2026-04-28 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='emaillog',
                    name='send_type',
                    field=models.CharField(choices=[('AUTO', 'Automático'), ('MANUAL', 'Manual'), ('REENVIO', 'Reenvío'), ('DESTINATARIO_ALTERNO', 'Destinatario Alterno')], default='AUTO', max_length=30),
                ),
                migrations.AddField(
                    model_name='emaillog',
                    name='sent_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[],
        ),
    ]
