# Generated by Django 6.0.2 on 2026-04-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emaillog_send_type_emaillog_sent_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emailconfig',
            constraint=models.UniqueConstraint(fields=('institution',), name='unique_email_config_per_tenant'),
        ),
    ]
