# Generated by Django 5.2.13 on 2026-04-27 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio'), ('INCOME', 'Ingresos'), ('EXPENSE', 'Gastos')], max_length=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='Casillero SRI')),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Banco')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código (Opcional/SRI)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['name'],
                'unique_together': {('institution', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Activo')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código Interno / Etiqueta')),
                ('purchase_date', models.DateField(verbose_name='Fecha de Compra')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Adquisición')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Residual (Salvamento)')),
                ('useful_life_years', models.PositiveIntegerField(verbose_name='Vida Útil (Años)')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Depreciación Acumulada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_as_asset', to='accounting.account', verbose_name='Cuenta de Activo')),
                ('account_depreciation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_as_depreciation', to='accounting.account', verbose_name='Cuenta Depreciación Acumulada')),
                ('account_expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_as_expense', to='accounting.account', verbose_name='Cuenta Gasto por Depreciación')),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['-purchase_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Asentado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20)),
                ('entry_type', models.CharField(choices=[('REGULAR', 'Regular'), ('ADJUSTMENT', 'Ajuste de Integridad')], default='REGULAR', max_length=20)),
                ('is_unbalanced', models.BooleanField(default=False, help_text='Marcado automático para asientos que no cumplen el balance Debe == Haber.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_for', models.ForeignKey(blank=True, help_text='Enlace al asiento original que este registro está corrigiendo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='accounting.journalentry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('date', models.DateField(verbose_name='Fecha de Depreciación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Depreciado')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas / Periodo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='accounting.fixedasset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_records', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Registro de Depreciación',
                'verbose_name_plural': 'Registros de Depreciaciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('key', models.CharField(choices=[('ASSET_CASH', 'Activo - Caja (Efectivo)'), ('ASSET_BANK', 'Activo - Bancos (Transferencia)'), ('ASSET_CXC', 'Activo - Cuentas por Cobrar Clientes'), ('LIABILITY_IVA', 'Pasivo - IVA Cobrado'), ('INCOME_SERVICES', 'Ingresos - Servicios Educativos'), ('LIABILITY_SUPPLIERS', 'Pasivo - Proveedores (Cuentas por Pagar)'), ('ASSET_TAX_CREDIT', 'Activo - IVA Crédito Tributario'), ('EQUITY_RETAINED_EARNINGS', 'Patrimonio - Resultados Acumulados / Utilidad del Ejercicio')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'verbose_name': 'Configuración Contable',
                'verbose_name_plural': 'Configuraciones Contables',
                'unique_together': {('institution', 'key')},
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Ahorros'), ('CHECKING', 'Corriente'), ('VIRTUAL', 'Billetera Virtual / Online')], default='CHECKING', max_length=20, verbose_name='Tipo de Cuenta')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Inicial')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.bank', verbose_name='Banco')),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='accounting.account', verbose_name='Cuenta Contable Asociada')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'unique_together': {('institution', 'bank', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('year', models.PositiveIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'unique_together': {('institution', 'year')},
            },
        ),
    ]
