# Generated by Django 5.2.8 on 2026-01-13 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_institution_sri_url_authorization_prod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio'), ('INCOME', 'Ingresos'), ('EXPENSE', 'Gastos')], max_length=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='Casillero SRI')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.institution')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Asentado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='users.institution')),
            ],
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='users.institution')),
            ],
            options={
                'unique_together': {('institution', 'year')},
            },
        ),
    ]
