# Generated by Django 5.2.8 on 2026-01-13 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('users', '0010_institution_sri_url_authorization_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AccountingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('ASSET_CASH', 'Activo - Caja (Efectivo)'), ('ASSET_BANK', 'Activo - Bancos (Transferencia)'), ('ASSET_CXC', 'Activo - Cuentas por Cobrar Clientes'), ('LIABILITY_IVA', 'Pasivo - IVA Cobrado'), ('INCOME_SERVICES', 'Ingresos - Servicios Educativos')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_configs', to='users.institution')),
            ],
            options={
                'verbose_name': 'Configuración Contable',
                'verbose_name_plural': 'Configuraciones Contables',
                'unique_together': {('institution', 'key')},
            },
        ),
    ]
