# Generated by Django 5.2.8 on 2026-01-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_account_id_alter_fiscalyear_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingconfig',
            name='key',
            field=models.CharField(choices=[('ASSET_CASH', 'Activo - Caja (Efectivo)'), ('ASSET_BANK', 'Activo - Bancos (Transferencia)'), ('ASSET_CXC', 'Activo - Cuentas por Cobrar Clientes'), ('LIABILITY_IVA', 'Pasivo - IVA Cobrado'), ('INCOME_SERVICES', 'Ingresos - Servicios Educativos'), ('LIABILITY_SUPPLIERS', 'Pasivo - Proveedores (Cuentas por Pagar)'), ('ASSET_TAX_CREDIT', 'Activo - IVA Crédito Tributario')], max_length=50),
        ),
    ]
