# Generated by Django 6.0.2 on 2026-04-29 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_account_institution_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingconfig',
            name='key',
            field=models.CharField(choices=[('ASSET_CASH', 'Activo - Caja (Efectivo)'), ('ASSET_BANK', 'Activo - Bancos (Transferencia)'), ('ASSET_CXC', 'Activo - Cuentas por Cobrar Clientes'), ('LIABILITY_IVA', 'Pasivo - IVA Cobrado'), ('INCOME_SERVICES', 'Ingresos - Servicios Educativos'), ('LIABILITY_SUPPLIERS', 'Pasivo - Proveedores (Cuentas por Pagar)'), ('ASSET_TAX_CREDIT', 'Activo - IVA Crédito Tributario'), ('EQUITY_RETAINED_EARNINGS', 'Patrimonio - Resultados Acumulados / Utilidad del Ejercicio'), ('EXPENSE_DISCOUNTS', 'Gastos - Descuentos Concedidos')], max_length=50),
        ),
        migrations.CreateModel(
            name='MonthlyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('is_closed', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_closures', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('institution', 'year', 'month')},
            },
        ),
    ]
