# Generated by Django 5.2.11 on 2026-02-24 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_bank_bankaccount'),
        ('users', '0011_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Activo')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código Interno / Etiqueta')),
                ('purchase_date', models.DateField(verbose_name='Fecha de Compra')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Adquisición')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Residual (Salvamento)')),
                ('useful_life_years', models.PositiveIntegerField(verbose_name='Vida Útil (Años)')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Depreciación Acumulada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_as_asset', to='accounting.account', verbose_name='Cuenta de Activo')),
                ('account_depreciation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_as_depreciation', to='accounting.account', verbose_name='Cuenta Depreciación Acumulada')),
                ('account_expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_as_expense', to='accounting.account', verbose_name='Cuenta Gasto por Depreciación')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='users.institution')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['-purchase_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Depreciación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Depreciado')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas / Periodo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_records', to='accounting.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='accounting.fixedasset')),
            ],
            options={
                'verbose_name': 'Registro de Depreciación',
                'verbose_name_plural': 'Registros de Depreciaciones',
                'ordering': ['-date'],
            },
        ),
    ]
