# Generated by Django 6.0.2 on 2026-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_fixedasset_depreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingconfig',
            name='key',
            field=models.CharField(choices=[('ASSET_CASH', 'Activo - Caja (Efectivo)'), ('ASSET_BANK', 'Activo - Bancos (Transferencia)'), ('ASSET_CXC', 'Activo - Cuentas por Cobrar Clientes'), ('LIABILITY_IVA', 'Pasivo - IVA Cobrado'), ('INCOME_SERVICES', 'Ingresos - Servicios Educativos'), ('LIABILITY_SUPPLIERS', 'Pasivo - Proveedores (Cuentas por Pagar)'), ('ASSET_TAX_CREDIT', 'Activo - IVA Crédito Tributario'), ('EQUITY_RETAINED_EARNINGS', 'Patrimonio - Resultados Acumulados / Utilidad del Ejercicio')], max_length=50),
        ),
    ]
