# Generated by Django 6.0.2 on 2026-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge/files/'),
        ),
    ]
