# Generated by Django 5.2.13 on 2026-04-27 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARCORequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('right_type', models.CharField(choices=[('ACCESS', 'Acceso'), ('RECTIFICATION', 'Rectificación'), ('CANCELLATION', 'Cancelación / Supresión'), ('OPPOSITION', 'Oposición'), ('PORTABILITY', 'Portabilidad')], max_length=20)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión Legal'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('EXECUTED', 'Ejecutado')], db_index=True, default='PENDING', max_length=20)),
                ('response_content', models.TextField(blank=True, help_text='Legal response to the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(help_text='Legal deadline to respond (usually 15 days)')),
                ('anonymization_performed', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField()),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=20)),
                ('is_reported_to_authority', models.BooleanField(default=False)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('accepted', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='privacy.policyversion')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('legal_basis', models.CharField(max_length=100)),
                ('data_categories', models.TextField()),
                ('retention_period', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
