# Generated by Django 6.0.2 on 2026-04-28 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcorequest',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='databreach',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='treatmentactivity',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
    ]
