# Generated by Django 5.2.11 on 2026-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcorequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión Legal'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('EXECUTED', 'Ejecutado')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
