# Generated by Django 5.2.13 on 2026-05-01 17:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_module_description_remove_module_is_active_and_more'),
        ('users', '0003_alter_institution_setup_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('mrr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active_customers', models.IntegerField(default=0)),
                ('grace_count', models.IntegerField(default=0)),
                ('suspended_count', models.IntegerField(default=0)),
                ('payments_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAYMENT_CONFIRMED', 'Pago Confirmado'), ('SUSPENDED', 'Cuenta Suspendida'), ('GRACE_ENTERED', 'Entró en Gracia'), ('EMAIL_SENT', 'Correo Enviado'), ('PAYMENT_ANOMALY', 'Anomalía de Pago'), ('FAILED_TASK', 'Tarea Fallida')], max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
