# Generated by Django 5.2.13 on 2026-05-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_dailykpi_subscriptionauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='included_modules',
            field=models.ManyToManyField(blank=True, related_name='included_in_plans', to='subscriptions.module'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
