# Generated by Django 5.2.13 on 2026-05-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_plan_included_modules_plan_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_trial_days', models.PositiveIntegerField(default=30)),
                ('grace_period_days', models.PositiveIntegerField(default=5)),
                ('auto_suspend', models.BooleanField(default=True)),
                ('reminder_days', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global SaaS',
                'verbose_name_plural': 'Configuración Global SaaS',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='contract_duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('TRIAL_ACTIVE', 'Prueba Activa'), ('EXPIRING', 'Por Vencer'), ('GRACE', 'En Gracia'), ('SUSPENDED', 'Suspendido'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20),
        ),
    ]
