# Generated by Django 5.2.13 on 2026-04-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_alter_academicperiod_id_alter_academicyear_id_and_more'),
        ('learning', '0004_lesson_meeting_date_lesson_meeting_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='academic_category',
            field=models.ForeignKey(blank=True, help_text='Categoría del sistema académico para sincronizar notas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_assignments', to='academic.evaluationcategory'),
        ),
    ]
