# apps/data_engine/quality/models.py
"""Immutable DTOs representing quality violations, statistics, scores and reports."""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class QualityViolation:
    """Represents a single rule violation in a validated record."""

    rule_code: str
    field: Optional[str]
    message: str
    severity: str  # INFO, WARNING, ERROR, CRITICAL
    value: Any = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "rule_code": self.rule_code,
            "field": self.field,
            "message": self.message,
            "severity": self.severity,
            "value": str(self.value) if self.value is not None else None,
        }


@dataclass(frozen=True)
class QualityRuleResult:
    """Result of running a specific rule against a single record or set of records."""

    rule_code: str
    passed: bool
    violations: List[QualityViolation] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "rule_code": self.rule_code,
            "passed": self.passed,
            "violations": [v.to_dict() for v in self.violations],
        }


@dataclass(frozen=True)
class QualityStatistics:
    """Aggregated stats detailing the outcome of a quality validation run."""

    total_records: int
    passed_records: int
    failed_records: int  # Records containing at least one ERROR or CRITICAL violation
    total_violations: int
    info_count: int
    warning_count: int
    error_count: int
    critical_count: int
    execution_time_ms: float
    rules_executed: int

    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_records": self.total_records,
            "passed_records": self.passed_records,
            "failed_records": self.failed_records,
            "total_violations": self.total_violations,
            "info_count": self.info_count,
            "warning_count": self.warning_count,
            "error_count": self.error_count,
            "critical_count": self.critical_count,
            "execution_time_ms": self.execution_time_ms,
            "rules_executed": self.rules_executed,
        }


@dataclass(frozen=True)
class QualityScore:
    """A numerical (0-100) and qualitative representation of data quality."""

    score: float
    rating: str  # EXCELLENT, GOOD, FAIR, POOR

    def to_dict(self) -> Dict[str, Any]:
        return {
            "score": round(self.score, 2),
            "rating": self.rating,
        }


@dataclass(frozen=True)
class QualityReport:
    """Comprehensive final report generated by the Quality Engine."""

    session_id: str
    template_code: str
    statistics: QualityStatistics
    score: QualityScore
    violations_by_record: Dict[int, List[QualityViolation]] = field(default_factory=dict)  # key: record_index
    created_at: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "session_id": self.session_id,
            "template_code": self.template_code,
            "statistics": self.statistics.to_dict(),
            "score": self.score.to_dict(),
            "violations_by_record": {
                str(k): [v.to_dict() for v in val]
                for k, val in self.violations_by_record.items()
            },
            "created_at": self.created_at,
        }
