# Generated by Django 5.2.13 on 2026-04-27 22:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('customer_type', models.CharField(choices=[('STUDENT', 'Académico (Estudiante)'), ('INDEPENDENT', 'Independiente')], default='STUDENT', max_length=20)),
                ('identification', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.OneToOneField(blank=True, limit_choices_to={'role': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='treasury.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20)),
                ('access_key', models.CharField(blank=True, max_length=49, null=True, unique=True, verbose_name='Clave de Acceso')),
                ('sri_version', models.CharField(default='1.0.0', max_length=10, verbose_name='Versión XML')),
                ('xml_content', models.TextField(blank=True, null=True, verbose_name='XML Firmado')),
                ('sri_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta SRI')),
                ('sri_authorization_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Autorización')),
                ('sri_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado SRI')),
                ('client_name', models.CharField(max_length=200)),
                ('client_ruc', models.CharField(max_length=13)),
                ('client_address', models.TextField(blank=True)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='treasury.customer')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='treasury.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='treasury.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='treasury.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_rate', models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('0.15'), '15%')], decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('is_recurring', models.BooleanField(default=False)),
                ('due_day', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_detail', to='treasury.charge')),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='treasury.invoice')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.paymentconcept')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.paymentconcept'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.paymentmethod'),
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('institution', 'identification'), name='unique_customer_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_code_per_institution'),
        ),
    ]
