# Generated by Django 6.0.2 on 2026-04-28 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emaillog_send_type_emaillog_sent_by'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='invoice',
                    name='email_attempts_count',
                    field=models.PositiveIntegerField(default=0, verbose_name='Intentos de Envío'),
                ),
                migrations.AddField(
                    model_name='invoice',
                    name='email_status',
                    field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('RETRYING', 'Reintentando')], default='PENDING', max_length=20, verbose_name='Estado Envío Email'),
                ),
                migrations.AddField(
                    model_name='invoice',
                    name='last_email_log',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_last_log', to='notifications.emaillog'),
                ),
                migrations.AddField(
                    model_name='invoice',
                    name='last_email_sent_at',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Último Envío Email'),
                ),
            ],
            database_operations=[],
        ),
    ]
