# Generated by Django 6.0 on 2026-01-12 19:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_charge_invoicedetail_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconcept',
            name='iva_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('0.15'), '15%')], decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
    ]
