# Generated by Django 6.0 on 2026-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_alter_paymentconcept_iva_rate'),
        ('users', '0008_institution_emission_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_code_per_institution'),
        ),
    ]
