# Generated by Django 6.0.2 on 2026-04-29 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_alter_creditnote_institution_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('establishment', models.CharField(default='001', max_length=3)),
                ('emission_point', models.CharField(default='001', max_length=3)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'establishment', 'emission_point'), name='unique_sequence_per_point')],
            },
        ),
    ]
