# Generated by Django 5.2.8 on 2026-01-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_alter_paymentmethod_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='access_key',
            field=models.CharField(blank=True, max_length=49, null=True, unique=True, verbose_name='Clave de Acceso'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sri_authorization_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Autorización'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sri_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Respuesta SRI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sri_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado SRI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sri_version',
            field=models.CharField(default='1.0.0', max_length=10, verbose_name='Versión XML'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xml_content',
            field=models.TextField(blank=True, null=True, verbose_name='XML Firmado'),
        ),
    ]
