# Generated by Django 6.0.2 on 2026-04-29 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailconfig_unique_email_config_per_tenant'),
        ('treasury', '0004_invoicesequence'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('institution', 'number'), name='unique_invoice_number_per_institution'),
        ),
    ]
