# Generated by Django 6.0.2 on 2026-04-30 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailconfig_unique_email_config_per_tenant'),
        ('treasury', '0005_alter_invoice_number_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), models.Q(('client_name', ''), _negated=True), _connector='OR'), name='invoice_student_or_client_name'),
        ),
    ]
