# Generated by Django 6.0.2 on 2026-04-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_alter_customer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('STUDENT', 'Académico (Estudiante)'), ('INDIVIDUAL', 'Individual'), ('COMPANY', 'Empresa / RUC'), ('WALKIN', 'Consumidor Final'), ('INDEPENDENT', 'Independiente')], default='STUDENT', max_length=20),
        ),
    ]
