# Generated by Django 5.2.8 on 2026-01-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_notice_target_course_notice_target_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notices/attachments/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
