# Generated by Django 5.2.8 on 2026-01-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_notice_attachment_notice_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messages/attachments/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'name')},
            },
        ),
    ]
