# Identificación
TP_ID_RUC = '01'
TP_ID_CEDULA = '02'
TP_ID_PASAPORTE = '03'

# Comprobantes (Compras)
COMPROBANTE_FACTURA = '01'
COMPROBANTE_NOTA_VENTA = '02'
COMPROBANTE_LIQUIDACION = '03'

# Comprobantes (Ventas)
TP_ID_CLIENTE_RUC = '04'
TP_ID_CLIENTE_CEDULA = '05'
TP_ID_CLIENTE_PASAPORTE = '06'
TP_ID_CLIENTE_CONSUMIDOR_FINAL = '07'

COMPROBANTE_VENTA_FACTURA = '18'

# Pagos
PAGO_OTROS_SISTEMA_FINANCIERO = '20'

# Tipos Proveedor
PROVEEDOR_RESIDENTE = '01'
PROVEEDOR_NO_RESIDENTE = '02'

# Parte Relacionada
PARTE_RELACIONADA_NO = 'NO'
PARTE_RELACIONADA_SI = 'SI'
