from django.db import models
from django.conf import settings
from users.models import Institution

class CourseGroup(models.Model):
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='course_groups', null=True, blank=True)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    icon = models.CharField(max_length=50, default='BookOpen')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('institution', 'name')
        verbose_name_plural = "Course Groups"

    def __str__(self):
        return self.name

class CourseTag(models.Model):
    group = models.ForeignKey(CourseGroup, on_delete=models.CASCADE, related_name='tags')
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('group', 'name')
        verbose_name_plural = "Course Tags"

    def __str__(self):
        return f"{self.group.name} > {self.name}"

class LMSCourse(models.Model):
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='lms_courses')
    instructor = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.SET_NULL, 
        null=True, 
        related_name='instructor_lms_courses'
    )
    title = models.CharField(max_length=255)
    subject = models.ForeignKey(
        'academic.Subject', 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='lms_courses',
        help_text="Materia académica vinculada"
    )
    subtitle = models.CharField(max_length=500, blank=True)
    description = models.TextField(blank=True)
    cover_image = models.ImageField(upload_to='learning/courses/', null=True, blank=True)
    
    # Monetization
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    is_public = models.BooleanField(default=False, help_text="Can be sold to external users")
    
    # AI & Metadata
    ai_summary = models.TextField(blank=True, help_text="Generated by AI")
    ai_keywords = models.JSONField(default=list, blank=True)
    
    is_active = models.BooleanField(default=True)
    tag = models.ForeignKey(
        CourseTag, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='courses'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class LMSEnrollment(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name='lms_enrollments'
    )
    course = models.ForeignKey(LMSCourse, on_delete=models.CASCADE, related_name='enrollments')
    enrolled_at = models.DateTimeField(auto_now_add=True)
    progress_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    is_completed = models.BooleanField(default=False)
    
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('completed', 'Completed'),
        ('dropped', 'Dropped'),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')

    class Meta:
        unique_together = ('user', 'course')

    def __str__(self):
        return f"{self.user.username} enrolled in {self.course.title}"
