# Generated by Django 5.2.11 on 2026-02-25 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto a cobrar', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Moneda (ej USD)', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20)),
                ('gateway_name', models.CharField(blank=True, help_text='Nombre proveedor ej. stripe, payphone', max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Token o ID remoto del proveedor', max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text='ID de Factura o Pedido que originó el pago', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Concepto ej. Pago de Mensualidad Septiembre', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(blank=True, max_length=50)),
                ('event_type', models.CharField(help_text='Tipo de evento: webhook, webhook_failed, charge_created', max_length=100)),
                ('payload', models.JSONField(help_text='Carga cruda JSON enviada o recibida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Registro de Pago (Log)',
                'verbose_name_plural': 'Registros de Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
