# Generated by Django 5.2.13 on 2026-04-27 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto a cobrar', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Moneda (ej USD)', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFYING', 'En Verificación'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20)),
                ('voucher_file', models.FileField(blank=True, help_text='Archivo de comprobante de depósito', null=True, upload_to='vouchers/%Y/%m/')),
                ('gateway_name', models.CharField(blank=True, help_text='Nombre proveedor ej. stripe, payphone', max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Token o ID remoto del proveedor', max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text='ID de Factura o Pedido que originó el pago', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Concepto ej. Pago de Mensualidad Septiembre', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(blank=True, max_length=50)),
                ('event_type', models.CharField(help_text='Tipo de evento: webhook, webhook_failed, charge_created', max_length=100)),
                ('payload', models.JSONField(help_text='Carga cruda JSON enviada o recibida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Registro de Pago (Log)',
                'verbose_name_plural': 'Registros de Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(help_text='Ej: stripe, paypal, mercadopago, payphone', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='¿Está habilitada esta pasarela para la institución?')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Si es True, usará credenciales/entorno Sandbox')),
                ('credentials', models.JSONField(blank=True, default=dict, help_text="Llaves API en formato JSON. Ej: {'client_id': '...', 'secret': '...'}")),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='users.institution')),
            ],
            options={
                'verbose_name': 'Configuración de Pasarela',
                'verbose_name_plural': 'Configuraciones de Pasarelas',
                'constraints': [models.UniqueConstraint(fields=('institution', 'gateway_name'), name='unique_gateway_per_institution')],
            },
        ),
    ]
