# Generated by Django 5.2.11 on 2026-02-26 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0011_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(help_text='Ej: stripe, paypal, mercadopago, payphone', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='¿Está habilitada esta pasarela para la institución?')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Si es True, usará credenciales/entorno Sandbox')),
                ('credentials', models.JSONField(blank=True, default=dict, help_text="Llaves API en formato JSON. Ej: {'client_id': '...', 'secret': '...'}")),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='users.institution')),
            ],
            options={
                'verbose_name': 'Configuración de Pasarela',
                'verbose_name_plural': 'Configuraciones de Pasarelas',
                'constraints': [models.UniqueConstraint(fields=('institution', 'gateway_name'), name='unique_gateway_per_institution')],
            },
        ),
    ]
