# Generated by Django 6.0.2 on 2026-04-28 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='is_orphaned',
            field=models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_orphaned',
            field=models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.'),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='users.institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.institution', verbose_name='Institución'),
            preserve_default=False,
        ),
    ]
