# Generated by Django 5.2.11 on 2026-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentgatewayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='voucher_file',
            field=models.FileField(blank=True, help_text='Archivo de comprobante de depósito', null=True, upload_to='vouchers/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFYING', 'En Verificación'), ('PAID', 'Pagado'), ('CANCELED', 'Cancelado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20),
        ),
    ]
