# Generated by Django 5.2.13 on 2026-04-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('local', 'Local / Custom (Ollama/vLLM)')], default='anthropic', max_length=20)),
                ('api_key', models.CharField(help_text='Clave API para el proveedor seleccionado', max_length=255)),
                ('model_name', models.CharField(default='claude-3-haiku-20240307', help_text='Nombre exacto del modelo (ej: gpt-4o, claude-3-opus)', max_length=100)),
                ('api_base_url', models.URLField(blank=True, help_text='URL base opcional (usado para Ollama o proxies)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to='users.institution')),
            ],
            options={
                'verbose_name': 'Configuración de Proveedor IA',
                'verbose_name_plural': 'Configuraciones de Proveedores IA',
                'unique_together': {('institution', 'provider')},
            },
        ),
    ]
