# Generated by Django 6.0.2 on 2026-04-29 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.institution')),
            ],
            options={
                'verbose_name': 'Departamento',
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('identification', models.CharField(max_length=20, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('contract_type', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('EVENTUAL', 'Eventual'), ('POR_OBRA', 'Por obra/servicio'), ('PASANTIA', 'Pasantía')], default='INDEFINIDO', max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='users.institution')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='payroll.employee')),
            ],
            options={
                'verbose_name': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobado'), ('PAID', 'Pagado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='users.institution')),
            ],
            options={
                'verbose_name': 'Periodo de Nómina',
                'unique_together': {('institution', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonus_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iess_personal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_to_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_rolls', to='users.institution')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Rol de Pagos Individual',
                'unique_together': {('period', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('item_type', models.CharField(choices=[('EARNING', 'Ingreso'), ('DEDUCTION', 'Descuento')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='users.institution')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payrollroll')),
            ],
            options={
                'verbose_name': 'Detalle de Nómina',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='payroll.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.institution')),
            ],
            options={
                'verbose_name': 'Cargo',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.position'),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.PositiveIntegerField(default=5)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='users.institution')),
            ],
            options={
                'verbose_name': 'Jornada Laboral',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.workshift'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('LATE', 'Atraso'), ('ABSENT', 'Falta'), ('PERMISSION', 'Permiso/Justificado')], default='NORMAL', max_length=20)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.institution')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='payroll.employee')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
