# Generated by Django 6.0.2 on 2026-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollroll',
            name='iess_patronal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollroll',
            name='provision_13th',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollroll',
            name='provision_14th',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollroll',
            name='provision_reserve_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identification',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('institution', 'identification')},
        ),
    ]
