# Generated by Django 6.0.2 on 2026-04-28 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passstep',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='ticketsurvey',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution'),
        ),
    ]
