# Generated by Django 5.2.11 on 2026-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_ticketattachment_ticketcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Progreso'), ('PENDING_APPROVAL', 'Pendiente Aprobación'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado'), ('REOPENED', 'Reabierto')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
