# Generated by Django 5.2.13 on 2026-04-27 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instrucciones para el estudiante.')),
                ('content_template', models.TextField(help_text='Texto base del documento con variables {{student_name}}, {{course_name}}, etc.')),
                ('requires_approval', models.BooleanField(default=True, help_text='Si es Falso, se aprueba y genera automáticamente.')),
                ('approver_role', models.CharField(choices=[('RECTOR', 'Rector'), ('TEACHER', 'Profesor'), ('ADMIN', 'Administrativo'), ('LOCAL_ADMIN', 'Administrador Local')], default='ADMIN', help_text='Rol requerido para aprobar esta solicitud.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], db_index=True, default='PENDING', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Motivo o justificación llenada por el estudiante.')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, help_text='Comentarios del aprobador (ej. motivo de rechazo).')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='procedures/generated/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_approved', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_requested', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='procedures.proceduretemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
