# Generated by Django 5.2.12 on 2026-03-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_alter_proceduretemplate_id_alter_studentrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduretemplate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
