# Generated by Django 6.0.2 on 2026-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_alter_proceduretemplate_id_alter_studentrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduretemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
