# Generated by Django 5.2.13 on 2026-04-27 22:05

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/logos/')),
                ('ruc', models.CharField(blank=True, max_length=13, verbose_name='RUC')),
                ('establishment_code', models.CharField(default='001', max_length=3, verbose_name='Cod. Establecimiento')),
                ('emission_point', models.CharField(default='001', max_length=3, verbose_name='Punto Emision')),
                ('obligado_contabilidad', models.BooleanField(default=False, verbose_name='Obligado a llevar contabilidad')),
                ('sri_environment', models.IntegerField(choices=[(1, 'Pruebas'), (2, 'Producción')], default=1, verbose_name='Ambiente SRI')),
                ('electronic_signature', models.FileField(blank=True, null=True, upload_to='institutions/signatures/', verbose_name='Firma Electrónica (.p12)')),
                ('signature_password', models.CharField(blank=True, max_length=255, verbose_name='Contraseña Firma')),
                ('special_taxpayer_number', models.CharField(blank=True, max_length=13, verbose_name='Nro. Contribuyente Especial')),
                ('sri_url_reception_test', models.URLField(default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline', verbose_name='URL Recepción (Pruebas)')),
                ('sri_url_authorization_test', models.URLField(default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline', verbose_name='URL Autorización (Pruebas)')),
                ('sri_url_reception_prod', models.URLField(default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline', verbose_name='URL Recepción (Producción)')),
                ('sri_url_authorization_prod', models.URLField(default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline', verbose_name='URL Autorización (Producción)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Institución Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('LOCAL_ADMIN', 'Administrador Local'), ('ACCOUNTANT', 'Auditor Contable'), ('RECTOR', 'Rector/Supervisor'), ('TEACHER', 'Profesor'), ('DECE', 'Consejero DECE'), ('MEDICO', 'Médico Dispensario'), ('PARENT', 'Padre/Representante'), ('STUDENT', 'Estudiante')], default='STUDENT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=10)),
                ('second_name', models.CharField(blank=True, default='', max_length=150)),
                ('second_surname', models.CharField(blank=True, default='', max_length=150)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='Ecuatoriana', max_length=50)),
                ('civil_status', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_LIBRE', 'Unión Libre')], default='', max_length=20)),
                ('titles', models.TextField(blank=True, default='', help_text='Títulos profesionales y masterados')),
                ('teaching_category', models.CharField(blank=True, choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C'), ('D', 'Categoría D'), ('E', 'Categoría E'), ('F', 'Categoría F'), ('G', 'Categoría G'), ('H', 'Categoría H'), ('I', 'Categoría I'), ('J', 'Categoría J')], default='', max_length=2)),
                ('representative_name', models.CharField(blank=True, default='', max_length=255)),
                ('representative_cedula', models.CharField(blank=True, default='', max_length=20)),
                ('representative_email', models.EmailField(blank=True, default='', max_length=254)),
                ('representative_address', models.TextField(blank=True, default='')),
                ('use_representative_for_billing', models.BooleanField(default=False)),
                ('secondary_phone', models.CharField(blank=True, default='', max_length=20)),
                ('children', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='parents', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario. Un usuario obtendrá todos los permisos otorgados a cada uno de sus grupos.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='permisos de usuario')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'cedula'), name='unique_cedula_per_institution')],
            },
        ),
    ]
