# Generated by Django 6.0.2 on 2026-04-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='setup_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='setup_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('READY', 'Listo'), ('FAILED', 'Fallido')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='wizard_completed',
            field=models.BooleanField(default=False),
        ),
    ]
