# Generated by Django 5.2.13 on 2026-05-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_institution_setup_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='setup_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('READY_MINIMAL', 'Infraestructura Base Lista'), ('READY_FULL', 'Configuración Completa'), ('FAILED', 'Fallido')], default='PENDING', max_length=20),
        ),
    ]
