# Generated by Django 6.0 on 2026-01-02 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date_user_gender_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
