# Generated by Django 5.2.8 on 2026-01-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='representative_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
