# Generated by Django 6.0 on 2026-01-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_representative_name_user_secondary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='emission_point',
            field=models.CharField(default='001', max_length=3, verbose_name='Punto Emision'),
        ),
        migrations.AddField(
            model_name='institution',
            name='establishment_code',
            field=models.CharField(default='001', max_length=3, verbose_name='Cod. Establecimiento'),
        ),
        migrations.AddField(
            model_name='institution',
            name='obligado_contabilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
