# Generated by Django 5.2.8 on 2026-01-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_institution_emission_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='electronic_signature',
            field=models.FileField(blank=True, null=True, upload_to='institutions/signatures/', verbose_name='Firma Electrónica (.p12)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='signature_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contraseña Firma'),
        ),
        migrations.AddField(
            model_name='institution',
            name='special_taxpayer_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='Nro. Contribuyente Especial'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sri_environment',
            field=models.IntegerField(choices=[(1, 'Pruebas'), (2, 'Producción')], default=1, verbose_name='Ambiente SRI'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='obligado_contabilidad',
            field=models.BooleanField(default=False, verbose_name='Obligado a llevar contabilidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
