# Generated by Django 5.2.8 on 2026-01-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_institution_electronic_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sri_url_authorization_prod',
            field=models.URLField(default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline', verbose_name='URL Autorización (Producción)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sri_url_authorization_test',
            field=models.URLField(default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline', verbose_name='URL Autorización (Pruebas)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sri_url_reception_prod',
            field=models.URLField(default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline', verbose_name='URL Recepción (Producción)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sri_url_reception_test',
            field=models.URLField(default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline', verbose_name='URL Recepción (Pruebas)'),
        ),
    ]
