# Generated by Django 5.2.11 on 2026-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_institution_sri_url_authorization_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario. Un usuario obtendrá todos los permisos otorgados a cada uno de sus grupos.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('LOCAL_ADMIN', 'Administrador Local'), ('ACCOUNTANT', 'Auditor Contable'), ('RECTOR', 'Rector/Supervisor'), ('TEACHER', 'Profesor'), ('PARENT', 'Padre/Representante'), ('STUDENT', 'Estudiante')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='permisos de usuario'),
        ),
    ]
