# Generated by Django 5.2.12 on 2026-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_institution_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_LIBRE', 'Unión Libre')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, default='Ecuatoriana', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_category',
            field=models.CharField(blank=True, choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C'), ('D', 'Categoría D'), ('E', 'Categoría E'), ('F', 'Categoría F'), ('G', 'Categoría G'), ('H', 'Categoría H'), ('I', 'Categoría I'), ('J', 'Categoría J')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='titles',
            field=models.TextField(blank=True, default='', help_text='Títulos profesionales y masterados'),
        ),
    ]
