# Generated by Django 5.2.12 on 2026-03-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_civil_status_user_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='representative_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='representative_cedula',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='representative_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='use_representative_for_billing',
            field=models.BooleanField(default=False),
        ),
    ]
