# Generated by Django 6.0.2 on 2026-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_representative_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('LOCAL_ADMIN', 'Administrador Local'), ('ACCOUNTANT', 'Auditor Contable'), ('RECTOR', 'Rector/Supervisor'), ('TEACHER', 'Profesor'), ('DECE', 'Consejero DECE'), ('MEDICO', 'Médico Dispensario'), ('PARENT', 'Padre/Representante'), ('STUDENT', 'Estudiante')], default='STUDENT', max_length=20),
        ),
    ]
