# apps/data_engine/components/loaders/models.py
"""Domain entities for the MAC Loader Engine & Dependency Resolution Framework.

Defines data structures used to represent entities as logical nodes and their loading plans:

- ``LoadNode``: Represents an entity node within a directed acyclic graph (DAG) of dependencies.
- ``DependencyCycle``: Encapsulates a detected circular dependency path and explanation.
- ``LoadPlan``: Consolidated outcome of dependency resolution, providing ordered nodes,
  execution groups by topological depth, and cycle reporting without database coupling.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, List, Optional, Set


@dataclass
class LoadNode:
    """Represents a logical loading node (entity) in the dependency resolution graph.

    Attributes:
        node_id: Unique identifier for this logical node or entity instance (e.g., "Institution_1", "Course").
        entity_name: Name of the conceptual entity (e.g., "Institution", "Course", "Student").
        dependencies: Set of ``node_id`` strings representing nodes that MUST be loaded before this node.
        payload_reference: Optional reference to data dicts, items, or records associated with this entity.
    """

    node_id: str
    entity_name: str
    dependencies: Set[str] = field(default_factory=set)
    payload_reference: Optional[Any] = None

    def __post_init__(self):
        if not isinstance(self.dependencies, set):
            self.dependencies = set(self.dependencies)


@dataclass
class DependencyCycle:
    """Represents a circular dependency detected during graph resolution.

    Attributes:
        cycle_path: Ordered list of ``node_id`` strings forming the cycle (e.g., ["A", "B", "C", "A"]).
        message: Human-readable diagnostic explanation of the cycle.
    """

    cycle_path: List[str]
    message: str


@dataclass
class LoadPlan:
    """Consolidated loading plan generated by the dependency planner.

    Attributes:
        ordered_nodes: Topologically sorted list of ``LoadNode`` items ready for sequential execution.
        execution_groups: List of node lists grouped by dependency level for future parallel execution.
                          Level 0 contains independent nodes; Level K contains nodes depending only on Levels < K.
        has_cycles: True if one or more circular dependencies prevented complete topological ordering.
        total_nodes: Total number of nodes submitted for planning.
        cycles: List of detected ``DependencyCycle`` objects when ``has_cycles`` is True.
        plan_id: Unique UUID4 identifier for this generated plan.
        timestamp: UTC ISO-8601 timestamp representing when the plan was generated.
    """

    ordered_nodes: List[LoadNode] = field(default_factory=list)
    execution_groups: List[List[LoadNode]] = field(default_factory=list)
    has_cycles: bool = False
    total_nodes: int = 0
    cycles: List[DependencyCycle] = field(default_factory=list)
    plan_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


__all__ = ["LoadNode", "DependencyCycle", "LoadPlan"]
