# Generated by Django 6.0 on 2026-01-02 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BEHAVIORAL', 'Conductual'), ('ACADEMIC', 'Académica'), ('POSITIVE', 'Positiva')], default='ACADEMIC', max_length=20)),
                ('description', models.TextField()),
                ('criticality', models.CharField(choices=[('LOW', 'Baja (Informativa)'), ('MEDIUM', 'Media (Atención)'), ('HIGH', 'Alta (Acción Requerida)')], default='LOW', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_observations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
