# Generated by Django 5.2.11 on 2026-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_academicyear_academicperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiod',
            options={'ordering': ['number'], 'verbose_name': 'Periodo Académico', 'verbose_name_plural': 'Periodos Académicos'},
        ),
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'Año Lectivo', 'verbose_name_plural': 'Años Lectivos'},
        ),
        migrations.AlterModelOptions(
            name='evaluationcategory',
            options={'verbose_name': 'Categoría de Evaluación', 'verbose_name_plural': 'Categorías de Evaluación'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Bloquea la calificación para este periodo'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Establecer como año activo actual'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Si está cerrado, no se permiten cambios globalmente'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.IntegerField(help_text='Identificador numérico del año'),
        ),
    ]
