# Generated by Django 5.2.12 on 2026-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_alter_academicperiod_id_alter_academicyear_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grading_type',
            field=models.CharField(choices=[('QUANTITATIVE', 'Cuantitativa (Números)'), ('QUALITATIVE', 'Cualitativa (Destrezas: DA, EP, I, NE)')], default='QUANTITATIVE', max_length=20),
        ),
    ]
