# Generated by Django 5.2.12 on 2026-03-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_course_grading_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grading_type',
            field=models.CharField(choices=[('INHERIT', 'Heredar del Curso'), ('QUANTITATIVE', 'Cuantitativa (0-10)'), ('QUALITATIVE_DESTREZAS', 'Cualitativa - Destrezas (DA, EP, I, NE)'), ('QUALITATIVE_PROYECTOS', 'Cualitativa - Proyectos (EX, MB, B, R)'), ('QUALITATIVE_COMPORTAMIENTO', 'Cualitativa - Comportamiento (A, B, C, D, E)')], default='INHERIT', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='grading_type',
            field=models.CharField(choices=[('QUANTITATIVE', 'Cuantitativa (0-10)'), ('QUALITATIVE_DESTREZAS', 'Cualitativa - Destrezas (DA, EP, I, NE)'), ('QUALITATIVE_PROYECTOS', 'Cualitativa - Proyectos (EX, MB, B, R)'), ('QUALITATIVE_COMPORTAMIENTO', 'Cualitativa - Comportamiento (A, B, C, D, E)')], default='QUANTITATIVE', max_length=50),
        ),
    ]
