# Generated by Django 5.2.12 on 2026-04-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='Dejar en blanco si es categoría principal. Si se selecciona, este aporte será sub-aporte de dicha categoría.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='academic.evaluationcategory'),
        ),
    ]
