# Generated by Django 6.0.2 on 2026-04-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_alter_academicperiod_id_alter_academicyear_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Si es privada, solo personal del DECE, Médicos y Administradores podrán verla.'),
        ),
        migrations.AddField(
            model_name='observation',
            name='referred_to',
            field=models.CharField(choices=[('TEACHER', 'Docente / General'), ('DECE', 'DECE (Consejería)'), ('MEDICO', 'Médico / Dispensario')], default='TEACHER', help_text='Departamento al que se deriva o pertenece este registro', max_length=20),
        ),
        migrations.AddField(
            model_name='observation',
            name='resolution',
            field=models.TextField(blank=True, help_text='Resolución o seguimiento dado por el departamento encargado'),
        ),
        migrations.AddField(
            model_name='observation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluationcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='type',
            field=models.CharField(choices=[('BEHAVIORAL', 'Conductual'), ('ACADEMIC', 'Académica'), ('POSITIVE', 'Positiva'), ('SOCIOEMOTIONAL', 'Socioemocional'), ('MEDICAL', 'Médica / Salud')], default='ACADEMIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
