# Generated by Django 5.2.13 on 2026-04-27 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('negative_count_threshold', models.IntegerField(default=3)),
                ('days_window', models.IntegerField(default=7)),
                ('include_low_grades', models.BooleanField(default=False)),
                ('grade_threshold', models.FloatField(default=5.0)),
                ('include_absences', models.BooleanField(default=False)),
                ('absence_threshold', models.IntegerField(default=5)),
                ('auto_create_case', models.BooleanField(default=True)),
                ('target_area', models.CharField(choices=[('DECE', 'DECE'), ('MEDICAL', 'Dispensario Médico'), ('EXTERNAL', 'Institución Externa')], default='DECE', max_length=20)),
                ('notify_dece', models.BooleanField(default=True)),
                ('notify_tutor', models.BooleanField(default=True)),
                ('notify_parents', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'verbose_name': 'Regla de Alerta',
                'verbose_name_plural': 'Reglas de Alerta',
            },
        ),
        migrations.CreateModel(
            name='BehaviorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('record_type', models.CharField(choices=[('POSITIVE', 'Positiva'), ('NEGATIVE_MILD', 'Negativa Leve'), ('NEGATIVE_SEVERE', 'Negativa Grave'), ('ACADEMIC', 'Académica'), ('SOCIOEMOTIONAL', 'Socioemocional')], max_length=30)),
                ('template', models.CharField(choices=[('PARTICIPATES', 'Participa activamente'), ('DOES_NOT_SUBMIT', 'No entrega tareas'), ('DISRUPTS_CLASS', 'Interrumpe clase'), ('FIGHTS', 'Pelea / agresión'), ('BULLYING', 'Acoso escolar'), ('TARDINESS', 'Llegada tardía reiterada'), ('GOOD_BEHAVIOR', 'Buen comportamiento'), ('HELPS_PEERS', 'Ayuda a compañeros'), ('OTHER', 'Otro (personalizado)')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_alert', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_records', to='academic.academicyear')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_records', to='academic.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_behavior_records', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_records', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_records', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Registro Conductual',
                'verbose_name_plural': 'Registros Conductuales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('area', models.CharField(choices=[('DECE', 'DECE'), ('MEDICAL', 'Dispensario Médico'), ('EXTERNAL', 'Institución Externa')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Seguimiento'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('derived_from_area', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_cases', to='academic.academicyear')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('parent_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_cases', to='health.behaviorcase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_cases', to=settings.AUTH_USER_MODEL)),
                ('behavior_records', models.ManyToManyField(blank=True, related_name='related_cases', to='health.behaviorrecord')),
            ],
            options={
                'verbose_name': 'Caso Conductual',
                'verbose_name_plural': 'Casos Conductuales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('follow_up_type', models.CharField(choices=[('INTERVIEW_STUDENT', 'Entrevista con Estudiante'), ('INTERVIEW_PARENT', 'Entrevista con Representante'), ('OBSERVATION', 'Observación'), ('AGREEMENT', 'Acuerdo/Compromiso'), ('REFERRAL', 'Derivación'), ('NOTE', 'Nota Interna')], max_length=30)),
                ('content', models.TextField()),
                ('agreements', models.TextField(blank=True, default='')),
                ('is_confidential', models.BooleanField(default=False, help_text='Solo visible para DECE/Médico')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cases/attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='health.behaviorcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
            ],
            options={
                'verbose_name': 'Seguimiento de Caso',
                'verbose_name_plural': 'Seguimientos de Caso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('family_context', models.TextField(blank=True, null=True)),
                ('academic_history', models.TextField(blank=True, null=True)),
                ('special_educational_needs', models.BooleanField(default=False)),
                ('sen_details', models.TextField(blank=True, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dece_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha DECE',
                'verbose_name_plural': 'Fichas DECE',
            },
        ),
        migrations.CreateModel(
            name='DeceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('agreements', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dece_visits', to='academic.academicyear')),
                ('counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dece_interventions', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dece_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervención DECE',
                'verbose_name_plural': 'Intervenciones DECE',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('chronic_conditions', models.TextField(blank=True, null=True)),
                ('regular_medication', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
            },
        ),
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='academic.academicyear')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orphaned', models.BooleanField(default=False, help_text='Indica si el registro fue rescatado durante una migración de integridad por falta de relación padre.')),
                ('behavior_score', models.FloatField(default=100.0)),
                ('attendance_score', models.FloatField(default=100.0)),
                ('academic_score', models.FloatField(default=100.0)),
                ('overall_risk', models.CharField(choices=[('GREEN', 'Bien'), ('YELLOW', 'Riesgo'), ('RED', 'Crítico')], default='GREEN', max_length=10)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('negative_count_7d', models.IntegerField(default=0)),
                ('has_open_case', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to='academic.academicyear')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Riesgo',
                'verbose_name_plural': 'Perfiles de Riesgo',
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
